travis:
  secure:
    BINSTAR_TOKEN: HhP4mEhkiSEhikceisDrmMybGrZe7hFsf687G7cCNrtF0bTKx/XBXHRWqu3CTQdLfHb1SrVdZnk/de63OLiMdQSOLzTl3BuVW8QlebfkNd5D2+POUz/pec/yRZ8Ij+rgp3BqYkZnSZdMu9JR99r3KprpX1OAtMKr3z4+WNgn3uc22o/hqMDcvI/jcBwe75ldYsBIqmpoVWujJ/nFW324NH8Bzf6slZWOfS1LX6/3bdSgTnbNbFOFZZOE596iP4qRD1sQb+E0bJBU0nJnLh9szWikm8Yky8qEaKYKtdC0lzutp8Kl7gMmNK+FBgzXOw/EaLadGdkr0Rzhm40oTXKZDU1Dz6lu9gtx9LBInDDYe1dvOs+EbHZXw3+GSx42vxUDJ8SyTqUQIAl2wAHYCmRP3Xhg04+/E2EznDr89khvY02y3ecku+Diesm6f4ThafFOevQTKXexixaoyAVxCG+DMA897HOGnxQbvQSjsNn2eosTUjsZDsIoeDz4BHsW4bg9lEP+Gl0KA6EKZXu42OCxAcATGX9tw/rTbq3Tshi318/E35W8RR7iTVYzqVqeocCyxHQffe5ihca2pqABt2MBPCjL/LitGQBmW2mT8vncCM/1G1Qy3rjFKpeSLiwgEfXp0qfrMYrccH8Es/+cwoXsok3Au2b63vxaPhCxVC1C/us=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
